### ISSUE TITLE
Info on proper use

### ISSUE THREAD

**Issue by docop** [m1cr0man/docker-netbooter#1] opened 2022-06-07 13:14 UTC
Hi  So i try to boot up your image, but i'm not quite sure how..  my router is 192.168.48.1 , and the client pc get ip assign as .7 . The docker server is on .10  I put already vmlinuz and initrd from a live iso into the folder.

 with this .. no boot image found at the client when lan boot. :
docker run --rm -d --net host --name=netbooter -v /home/userxy/httproot:/netboot/httproot \
	-e DOMAINNAME=localdomain \
	-e DNSSERVERS="1.1.1.1,192.168.48.1" \
	-e NETPREFIX=192.168.48 \
	-e RANGESTART=7 -e RANGEEND=14 m1cr0man/netbooter:latest

thanks in advance

**Comment by m1cr0man** [comment] 2022-06-07 13:22
Hi there!

**Comment by m1cr0man** [comment] 2022-06-07 13:30
Hi.. Sorry commenting on mobile is hard haha.

So the problem is that this image is designed only to be used when either the authorative DHCP component can be enabled, or another DHCP server can be configured to point to it for boot data.

What you're looking for in your environment is a proxy DHCP server configuration which will serve a boot image on a network with an existing authorative DHCP server (that I'm assuming doesn't let you configure a boot server).

The only way I know how to do this is with dnsmasq. The name is deceiving but it can run as a proxy DHCP server for exactly this use case.

I have a configuration for NixOS to do this here: https://github.com/m1cr0man/nix-configs/blob/main/modules/servers/netbooter/default.nix 

What you could do is find another docker image for dnsmasq and configure it in conjunction with my docker image for the boot server, omitting some of the variables as detailed in the README.

Alternatively if you can wait a bit I could try and switch this image to dnsmasq tonight (if I can find a non breaking way to do so)

**Comment by docop** [comment] 2022-06-07 15:14
Hi  no problem on the mobile writing. hehe.
 As on dnsmasq i did try another with no good result and over openwrt, they have a tftp, but it can't find the file over the other server or on the local..  So yes, if you can put dnsmasq this can be quite great.
thanks again

**Comment by m1cr0man** [comment] 2022-06-08 09:52
Ive made a PR #2 which switches to dnsmasq and updates the README with new DHCP configuration info. I published it as m1cr0man/netbooter:dnsmasq on Docker Hub for now. If you could test it and let me know if it works for you that would be great :)

**Comment by docop** [comment] 2022-06-08 15:05
Hi It look quite terrific, it look to boot and go to your container. Just missing the menu or load somehow.. here is 

docker run --rm --net host --name=netbooter -v /home/userlxc/httproot:/netboot/httproot --cap-add=NET_ADMIN
	-e DNSSERVERS="1.1.1.1,192.168.41.1" \
	-e NETPREFIX=192.168.41 \
	-e RANGESTART=11 -e RANGEEND=14 \
	m1cr0man/netbooter:dnsmasq

 Not sure for the menu.ipxe if i need to download before and add perhaps : 
-v /home/userlxc/httproot/external:/netboot/httproot/external

docker srv on ..41.9  and on the client it tell :  

http://192.168.41.9:8069/menu.ipxe  :no such file or directory

thanks again

**Comment by m1cr0man** [comment] 2022-06-08 15:08
Yea you just need to copy the one from this repo and add your own netboot images, but it looks like it's working other than that 😀 see the bottom of the readme about adding images

**Comment by m1cr0man** [comment] 2022-06-08 15:10
By the way if your router already serves DHCP leases then I recommend using proxy mode instead

**Comment by m1cr0man** [comment] 2022-06-11 13:05
@docop Did you get sorted? 🙂

**Comment by docop** [comment] 2022-06-11 18:15
Yess You are the man! hehe. I got it working with Fatdog os, as only 2 file needed and seem it don't require much.
 I try with other os and fail to load up more file or so. But for the booting and show the menu, it do work.

i base my try on the live asset from ; 
https://github.com/netbootxyz/netboot.xyz/blob/development/endpoints.yml
  like with a garuda :
 ```
garuda-xfce:  /garuavr
    path: /asset-mirror/releases/download/220428-fdf20131/
    files:
    - amd_ucode.img
    - desktopfs.sfs
    - intel_ucode.img
    - livefs.sfs
    - initramfs.img
    - mhwdfs.sfs
    - rootfs.sfs
    - vmlinuz
    os: garuda
    flavor: xfce

```
wget https://github.com/netbootxyz/asset-mirror/releases/download/220428-fdf20131/  each file
  and into the menu :
:garu
imgfree
kernel http://${dhcp-server}:8069/garuavr/vmlinuz nouveau.modeset=1 i915.modeset=1 driver=free initrd=initrd.magic
initrd http://${dhcp-server}:8069/garuavr/initramfs.img
boot

 But while it load a bit, it give : waiting 30sec  mounting /dev/disk/by-label - to  run/miso/bootmnt
 then go to a prompt.

--
And a simpler one, centos rocky with 2 file, but give issues as: 
_warning for multipath sibling of sda_
dracut-initqueue 902  warning dracut-initqueue timeout -starting timeout scripts

curl -Lo /httproot/rock85/RockyLinux-8.5.initrd https://download.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os/images/pxeboot/initrd.img
curl -Lo /httproot/rock85/RockyLinux-8.5-vmlinuz https://download.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os/images/pxeboot/vmlinuz

-- 
I try to put netbootxyz as another item, but it fail.
:netbootxyz
kernel http://${dhcp-server}:8069/netbootxyz/memdisk iso raw
initrd http://${dhcp-server}:8069/netbootxyz/netboot.xyz.iso
boot
  
 -i replace .iso by file:  netboot.xyz.kpxe, but error. And not luck with direct load  by changing the line to :
chain --autofree http://boot.netboot.xyz

Thanks again appreciated

**Comment by m1cr0man** [comment] 2022-06-11 21:48
Great to hear it worked :) Sounds like you need to sort out your iPXE scripts though for the other images. For example, here is their [rocky linux boot script](https://github.com/netbootxyz/netboot.xyz/blob/development/roles/netbootxyz/templates/menu/rockylinux.ipxe.j2#L65-L66). You would need to adapt this to your own paths to get a bootable system. Booting from the iso or kpxe files won't work - you need the kernel and initrd/bzimage for the relevant distribution.

I'm gonna close this ticket now and work on getting the PR merged to master + automating publishing of this image.

**Closed as completed** 2023-06-30 21:39 UTC
